### ISSUE TITLE
Fiji - About ImageJ error

### ISSUE THREAD

**Issue by vmiller** [fiji/fiji#115]
Choosing the "About ImageJ" from the "Fiji" menu causes a Console window to open with the following error : 

[WARNING] About folder '/Applications/Fiji.app/about' does not exist.
[ERROR] Module threw exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at io.scif.AbstractMetadata.get(AbstractMetadata.java:122)
	at io.scif.services.DefaultDatasetIOService.updateDataset(DefaultDatasetIOService.java:206)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:130)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:109)
	at io.scif.services.SCIFIODatasetService.open(SCIFIODatasetService.java:165)
	at net.imagej.app.AboutImageJ.createDataset(AboutImageJ.java:154)
	at net.imagej.app.AboutImageJ.run(AboutImageJ.java:129)
	at org.scijava.command.CommandModule.run(CommandModule.java:201)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:181)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)

**Comment by vmiller** [comment]
Sorry, I should also have included that this is on MacOS 10.9.5 and using the current continuous release download.  The Life Line version from November 2014 does not have this issue.

**Comment by ctrueden** [comment]
@vmiller Thanks for the report. There are a couple of different things going on here. I pushed some fixes to the appropriate places (see above), which we will test and upload before the end of next week.

**Comment by ctrueden** [comment]
The relevant fixes have been released and uploaded to the ImageJ update site!
