### ISSUE TITLE
Huang Binarization Index Out of Bounds

### ISSUE THREAD

**Issue by NightRa** [fiji/fiji#131]
Huang Binarization on the attached image gives an `Index Out of Bounds`:
```
(Fiji Is Just) ImageJ 2.0.0-rc-41/1.50d; Java 1.6.0_24 [64-bit]; Windows NT (unknown) 6.2; 611MB of 12179MB (5%)
 
java.lang.ArrayIndexOutOfBoundsException: 214
	at fiji.threshold.Auto_Threshold.Huang(Auto_Threshold.java:475)
	at fiji.threshold.Auto_Threshold.exec(Auto_Threshold.java:302)
	at fiji.threshold.Auto_Threshold.run(Auto_Threshold.java:219)
	at ij.IJ.runUserPlugIn(IJ.java:212)
	at ij.IJ.runPlugIn(IJ.java:176)
	at ij.Executer.runCommand(Executer.java:132)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:662)
```
[2.1_median.jpg](https://cloud.githubusercontent.com/assets/2140983/10854178/bf2a10c6-7f42-11e5-9bc3-e2afc7520192.jpg) - The image causing the error.

**Comment by ctrueden** [comment]
Thanks for the report. I can reproduce this bug.

It only happens with [Auto Threshold](http://imagej.net/Auto_Threshold), not with the built-in Threshold command's Huang option. It also does not happen with the new ImageJ Ops implementation (ported from Auto_Threshold). Comparing the implementations, it's not intuitively obvious why one works and the other fails, so it will take some more in-depth debugging to sort it out.

**Comment by rcatwood** [comment]
See recent thread on ImageJ mailing list , I had a similar issue using Huang's method in the Auto Threshold plugin . G. Landini is aware of it... 

Re: Autothresholding results;  (was FW: Threshold is giving an incomplete range ?)

R.Atwood:

[blur10blob16.zip](https://github.com/fiji/fiji/files/1041898/blur10blob16.zip)



> Also, for some reason Autothresh -> Huang seems to consistently give a 
> segfault in processing the one with Gaussian blur 10 ?

G. Landini:
Yes, I can reproduce it in that image. Had a look at the source, seems to be an array dimension issues. The original code ported from Emre Celebi's implementation was re-written by Johannes Schindelin in 2011 to make it more efficient in handling 16bit data.  I will compare the old and new code results. 
Thanks for reporting these issues. The IJ applet still uses E Celebi's code.

**Comment by landinig** [comment]
Thanks. I was not aware of the early report, only the recent one.
Really all these methods are very slow on 16bit images and were developed originally for 8 bit images. 
I will look in detail into all this but in the mean time I can only suggest to either download the one on my page (which includes the original Huang code) which does not give that error and keep Johannes's code which is very quick as Huang2. I also noted that the two Huang versions do not return exactly the same result with certain images. The original Huang code is painfully slow in 16bits.
It appears that having converted the code to process 16bit histograms brought other problems (the Mean and Otsu methods had also a problem with certain images, now fixed).
I will review all the methods again, and will report when done.
