### ISSUE TITLE
Startup crash after FiJi update 2016-09-15

### ISSUE THREAD

**Issue by PierreMuller** [fiji/fiji#150]
Following automatic update of Fiji,
Fiji is not able to start anymore.

Using DEBUG method for Windows-64bit by renaming executable to debug.exe
I get the backtrace below.

  Last update seemed to only update bioformats jars.
Could be related to new 5.2.2 bioformat release.

Pierre Muller

[DEBUG] Created service 'io.scif.io.DefaultNIOService' in 0 ms
[DEBUG] Creating service: io.scif.ome.services.DefaultOMEMetadataService
Error while executing the main() method of class 'net.imagej.Main':
java.lang.IllegalArgumentException: Invalid service: io.scif.ome.services.DefaultOMEMetadataService
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:280)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166)
        at org.scijava.Context.<init>(Context.java:277)
        at org.scijava.Context.<init>(Context.java:234)
        at org.scijava.Context.<init>(Context.java:174)
        at org.scijava.Context.<init>(Context.java:160)
        at net.imagej.ImageJ.<init>(ImageJ.java:79)
        at net.imagej.Main.launch(Main.java:61)
        at net.imagej.Main.main(Main.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.UnsupportedClassVersionError: ome/xml/model/enums/EnumerationException : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
        at java.lang.Class.getConstructor0(Class.java:2699)
        at java.lang.Class.newInstance0(Class.java:326)
        at java.lang.Class.newInstance(Class.java:308)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:302)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
        ... 17 more

**Comment by PierreMuller** [comment]
As it seems mainly link to bioformat,
I also submitted a bug report to openmicroscopy:

https://github.com/openmicroscopy/bioformats/issues/2578

Pierre Muller

**Comment by PierreMuller** [comment]
With the help of Sébastien Besson,
I was able to start Fiji again, after change the ImageJ.cfg 
to point to a newer version of javaw.exe.

The Fiji installed javaw was version 1.6.0_24
which generated the error above,
while new version is: 1.8.0-101.

  According to Sébastien Besson, it is the scijava part of core 1.6.0 that is too old
for new bioformats, but I have no ideas how such version dependencies are handled
in Fiji.

  With this updated javaw executable all seems to work.

  Is it possible to update the java jre using the updater for people that are not using java elsewhere?

Pierre Muller

**Comment by ctrueden** [comment]
> Is it possible to update the java jre using the updater for people that are not using java elsewhere?

No, not using the updater. See [these instructions](http://imagej.net/Frequently_Asked_Questions#How_do_I_launch_ImageJ_with_a_different_version_of_Java.3F).

In general, it is best practice to run ImageJ and Fiji with Java 8 these days. If you [download a fresh Fiji](http://fiji.sc/#download), it comes bundled with Java 8 out of the box.

See also:

* [ImageJ HOWTO - Java 8, Java 6, Java 3D](http://imagej.net/2016-05-10_-_ImageJ_HOWTO_-_Java_8,_Java_6,_Java_3D)
