### ISSUE TITLE
Error sometimes appears when running my ImageJ macro - should I be worried?

### ISSUE THREAD

**Issue by margiezilla** [fiji/fiji#151]
Error sometimes appears - should I be worried? This is the error:

`Error while executing the main() method of class 'net.imagej.Main':
java.lang.NullPointerException
	at net.imagej.legacy.IJ1Helper.setVisible(IJ1Helper.java:295)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:129)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:155)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:140)
	at org.scijava.AbstractGateway.launch(AbstractGateway.java:101)
	at net.imagej.Main.launch(Main.java:62)
	at net.imagej.Main.main(Main.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)`

The error only seems to occur with one of two flycircuit neuron NRRDs (image stacks) that I am using, but I think the code is merging them just fine, because when I check the merged images I think they are ok. The macro is nothing very fancy, but I am mystified as to why ImageJ occasionally throws up an error with certain images.

The ImageJ macro code is as follows:
'// ImageJ macro intersectflycircuitwithbrainreg.ijm
// Designed to open NRRD files for 3 channels of registered brain
// and then to merge with a provided FlyCircuit neuron, then save 
// as TIFF
// Written by Margaret Ho - margaret.ho@jhmi.edu

//EXAMPLE USAGE:
// PATH=$PATH:~/Programs/Fiji.app/
// ImageJ-linux64 -macro intersectflycircuitwithbrainreg.ijm "/full/path/to/bluenc82/channel.nrrd /full/path/to/greengfp/channel.nrrd /full/path/to/redTH/channel.nrrd /full/path/to/flycircuitneuron.nrrd /full/path/to/save/to/ uniquelabel"
// argument 1: /full/path/to/bluenc82/channel.nrrd
// argument 2: /full/path/to/greengfp/channel.nrrd
// argument 3: /full/path/to/redTH/channel.nrrd
// argument 4: /full/path/to/flycircuitneuron.nrrd
// argument 5: /full/path/to/save/to/
// argument 6: uniquelabel
// ALL THE ARGUMENTS NEED TO BE SURROUNDED BY "QUOTES AND SEPARATED BY SPACES"

args = split(getArgument," ");

first_path = args[args.length-6];
second_path = args[args.length-5];
third_path = args[args.length-4];
flycirc_path = args[args.length-3];
wheretosave = args[args.length-2];
id = args[args.length-1];

flycirc_parts=split(flycirc_path,"/");
flycirc_channel= flycirc_parts[flycirc_parts.length-1];
flycirc_parts2=split(flycirc_channel,".");
flycirc_name=flycirc_parts2[flycirc_parts2[0]];

third_parts=split(third_path,"/");
third_channel= third_parts[third_parts.length-1];
second_parts=split(second_path,"/");
second_channel= second_parts[second_parts.length-1];
first_parts=split(first_path,"/");
first_channel= first_parts[first_parts.length-1];

setBatchMode(true);

open(first_path);
open(second_path);
open(third_path);
open(flycirc_path);

run("Merge Channels...", "c3="+first_channel+" c2="+second_channel+" c1="+third_channel+" c5="+flycirc_channel+" create");

selectWindow("Composite");
saveAs("Tiff", wheretosave+id+"_"+flycirc_name+"_merge.tif");
close();

run("Quit");'

**Comment by ctrueden** [comment]
Thanks for the report, @margiezilla!

Are you able to reproduce that error every time with a particular dataset? If so, could you share the dataset which reproduces it? Our ideal goal here would really be to get down to a [Minimal, Complete, Verifiable Example (MCVE)](http://stackoverflow.com/help/mcve), to make it as easy as possible for us to investigate and fix this bug.

**Comment by margiezilla** [comment]
Yes, I can share the dataset. This is how I run the code to try to merge channel01.nrrd, channel02.nrrd, channel03.nrrd with a given flycircuit_neuron.nrrd using my ImageJ macro

`ImageJ-linux64 -macro /path/to/intersectflycircuitwithbrainreg.ijm /path/to/channel01.nrrd  /path/to/channel02.nrrd  /path/to/channel03.nrrd /path/to/vfb_00013686.nrrd /path/to/output/folder/ label`

Yes, it works fine with some flycircuit NRRDs (attached), but others it gives me the error. However I think still runs the code because I get the merged files. I am just worried about the error and don't know why I am getting it.

What I have found is that vfb_00013686.nrrd works but vfb_00013777.nrrd throws up an error and I can't figure out why!

Here are the files including the .ijm (ImageJ macro) code that I wrote:
[intersectflycircuitwithbrainreg.ijm.zip](https://github.com/fiji/fiji/files/522849/intersectflycircuitwithbrainreg.ijm.zip)
[channel01.nrrd.zip](https://github.com/fiji/fiji/files/522847/channel01.nrrd.zip)
[channel02.nrrd.zip](https://github.com/fiji/fiji/files/522852/channel02.nrrd.zip)
[channel03.nrrd.zip](https://github.com/fiji/fiji/files/522850/channel03.nrrd.zip)
[vfb_00013686.nrrd.zip](https://github.com/fiji/fiji/files/522848/vfb_00013686.nrrd.zip)
[vfb_00013777.nrrd.zip](https://github.com/fiji/fiji/files/522851/vfb_00013777.nrrd.zip)

I would appreciate any help! Thank you.

**Comment by margiezilla** [comment]
They all have the same number of images in the stack (218 images), so that is not the issue.

**Comment by ctrueden** [comment]
@margiezilla Thank you very much for the data and clean steps to reproduce.

I think this is a race condition. I was able to reproduce the issue with `vfb_00013686` as well... sometimes.

I have not had time to debug why yet, and probably won't in the near future. If things are working for you in the meantime, that's good.

**Comment by margiezilla** [comment]
Thanks for taking the time to respond. Unfortunately, I actually can't merge the first channel out of all my channels, so it is still a pretty problematic bug :(
