### ISSUE TITLE
Problem with running a plugin

### ISSUE THREAD

**Issue by William87** [fiji/fiji#155]
Exception message:

(Fiji Is Just) ImageJ 2.0.0-rc-54/1.51h; Java 1.8.0_66 [64-bit]; Windows 10 10.0; 55MB of 6048MB (<1%)
 
java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Sheet
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at ij.IJ.runUserPlugIn(IJ.java:215)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Sheet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

**Comment by cmci** [comment]
Hi @William87 

I think without explaining which plugin you are trying to run, it will be very difficult for anyone to think about what the problem is.

**Comment by William87** [comment]
Hi Kota Miura,

sorry, the plugin I am talking about is Imaging FCS 1.491. You can find it to the following link: http://www.dbs.nus.edu.sg/lab/BFL/imfcs_image_j_plugin.html.

Thank you for your interest.

**Comment by cmci** [comment]
You need to install Apache POI, and your error log is telling that you did not. Please carefully read the instruction provided in the FCS plugin page you linked, and setup the correct environment for the plugin.

**Comment by imagejan** [comment]
@William87 you might also contact the original authors and ask them to set up an [update site](http://imagej.net/Update_Sites), which would make it much easier to use their plugin (i.e. installation by a single click).

**Comment by William87** [comment]
I installed Apache POI coping the whole poi-3.15 folder into the jars folder of Fiji. I followed as well all the procedure provided in the FCS plugin page, nevertheless I get the above exception message.

**Comment by ctrueden** [comment]
We cannot offer support here for non-Fiji third party plugins, especially those installed manually without using update sites. If you are still having this issue, and still need help, you could make a post on the [ImageJ Forum](http://forum.imagej.net/) about it.

**Comment by imagejan** [comment]
For the record: there is now an update site `http://sites.imagej.net/ImagingFCS/` that can be [activated in the updater](https://imagej.net/Following_an_update_site) to install the plugin and its dependencies.

See also [this discussion](http://forum.imagej.net/t/upload-site-for-plugin-downloadable-jar/7360?u=imagejan) on the ImageJ forum.
