### ISSUE TITLE
Open GL exception

### ISSUE THREAD

**Issue by aderzelle** [fiji/fiji#159]
Hello everyone,

When trying to use the 3D plugin of Fiji, on Windows 10 (graphic card: AMD Radeon HD 7400M Series), I get the following error 

"
3D [dev] 1.6.0-scijava-2-pre11-daily-experimental daily

com.jogamp.opengl.GLException: J3D-Renderer-1: createImpl ctx !ARB but ARB is used, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL4bc/GL4bc.hw], current: 1.1 (Compat profile, compat[], hardware) - 1.1.0
	at jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl(WindowsWGLContext.java:404)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at org.scijava.java3d.JoglPipeline.createNewContext(JoglPipeline.java:6412)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:4602)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:2376)
	at org.scijava.java3d.Renderer.doWork(Renderer.java:881)
	at org.scijava.java3d.J3dThread.run(J3dThread.java:271)
Exception occurred in RenderingErrorListener:
java.lang.RuntimeException
	at ij3d.ImageWindow3D$ErrorListener.errorOccurred(ImageWindow3D.java:330)
	at org.scijava.java3d.VirtualUniverse.notifyRenderingErrorListeners(VirtualUniverse.java:1198)
	at org.scijava.java3d.NotificationThread.processNotifications(NotificationThread.java:86)
	at org.scijava.java3d.NotificationThread.run(NotificationThread.java:104)
nFrames = 1
"

Do you have any idea of what's going on? 

Thanks a lot.

**Comment by ctrueden** [comment]
Yes, this is being discussed at fiji/3D_Viewer#17.

There is a fixed launcher, which you can [download here](http://sites.imagej.net/Aschain/fiji-win64.exe-20161102105633). I have not formally released and uploaded this fix yet, but it is reported as working by many Windows users.
