### ISSUE TITLE
ArgumentError: invalid Java class or interface: ij.CompositeImage

### ISSUE THREAD

**Issue by camlloyd** [fiji/fiji#165]
The error below is now produced in the interpreter log when I try to run any JRuby code. 

I have just had to reinstall Fiji so I am wondering if it is to do with that?

`ArgumentError: invalid Java class or interface: ij.CompositeImage
  java_import at file:/Applications/Fiji.app/jars/jruby-core-1.7.12.jar!/jruby/java/core_ext/object.rb:34
          map at org/jruby/RubyArray.java:2409
  java_import at file:/Applications/Fiji.app/jars/jruby-core-1.7.12.jar!/jruby/java/core_ext/object.rb:22
       (root) at New_.rb:6
org.jruby.embed.EvalFailedException: (ArgumentError) invalid Java class or interface: ij.CompositeImage
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:118)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:146)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:177)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jruby.exceptions.RaiseException: (ArgumentError) invalid Java class or interface: ij.CompositeImage
	at Object.java_import(file:/Applications/Fiji.app/jars/jruby-core-1.7.12.jar!/jruby/java/core_ext/object.rb:34)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2409)
	at Object.java_import(file:/Applications/Fiji.app/jars/jruby-core-1.7.12.jar!/jruby/java/core_ext/object.rb:22)
	at RUBY.(root)(New_.rb:6)`

**Comment by camlloyd** [comment]
Apologies, I have fixed this. It was due to a JDK version conflict!
