### ISSUE TITLE
"Illegal use of nonvirtual function call" in --headless mode

### ISSUE THREAD

**Issue by Excludos** [fiji/fiji#207]
Could be similar to a bug from 2014: http://fiji.sc/bug/732.html

Attempting to run a macro command such as

```
run("Image Sequence...", "open=" + inPath + " sort");
```

with `-macro --headless --console` gives off the error:

```text
java.lang.VerifyError: (class: ij/gui/GenericDialog, method: repaint signature: ()V) Illegal use of nonvirtual function call
        at ij.plugin.FolderOpener.showDialog(FolderOpener.java:358)
        at ij.plugin.FolderOpener.run(FolderOpener.java:116)
        at ij.IJ.runPlugIn(IJ.java:187)
        at ij.Executer.runCommand(Executer.java:137)
        at ij.Executer.run(Executer.java:66)
        at ij.IJ.run(IJ.java:297)
        at ij.macro.Functions.doRun(Functions.java:601)
        at ij.macro.Functions.doFunction(Functions.java:96)
        at ij.macro.Interpreter.doStatement(Interpreter.java:230)
        at ij.macro.Interpreter.doStatements(Interpreter.java:218)
        at ij.macro.Interpreter.run(Interpreter.java:115)
        at ij.macro.Interpreter.run(Interpreter.java:85)
        at ij.macro.Interpreter.run(Interpreter.java:96)
        at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
        at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:139)
        at ij.IJ.runMacroFile(IJ.java:148)
        at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:952)
        at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:949)
        at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:899)
        at net.imagej.legacy.IJ1Helper.runMacroFile(IJ1Helper.java:949)
        at net.imagej.legacy.LegacyCommandline$Batch.handle(LegacyCommandline.java:213)
        at org.scijava.console.DefaultConsoleService.processArgs(DefaultConsoleService.java:93)
        at net.imagej.legacy.LegacyConsoleService.processArgs(LegacyConsoleService.java:76)
        at net.imagej.Main.launch(Main.java:64)
        at net.imagej.Main.main(Main.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at fiji.Main.main(Main.java:173)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
```

repost of https://forum.image.sc/t/unable-to-run-any-commands-in-headless-mode-and-console-app-not-exiting/19777 as this is probably a better place for bug reporting.

**Comment by Excludos** [comment]
Issue has been solved in version using Java8. I had in the moment forgotten that I downloaded an older version due to Bio-formats in the new one not functioning properly. Ended up with a mix mash of new version of Fiji with old bio formats plugin and it is now working properly.
