### ISSUE TITLE
fiji freezing when opening existing macros

### ISSUE THREAD

**Issue by agclark12** [fiji/fiji#217]
I'm having a problem where fiji completely freezes whenever I open an existing macro. As soon as the macro loads in the script editor, the editor window and all of fiji freezes and I have to force quit. This happens whether I open the macro by dragging or if I open via the menu. This started with a current update, and I've tried completely reinstalling my fiji and still have the same problem. Running up-to-date fiji on osx 10.13.6 (HighSierra).

anyone else having this issue?

thanks!

**Comment by ctrueden** [comment]
@agclark12 Thanks for the report. Can you please try troubleshooting according to these directions?

https://imagej.net/Troubleshooting#If_ImageJ_freezes_or_hangs

**Comment by agclark12** [comment]
@ctrueden yes, sorry for not including it before. actually, while getting the stack dump, i realized that if I wait about a minute and half, the console shows me an exception and then I can use the editor again. here's the stack dump:

<pre>
"AWT-EventQueue-0" prio=6 id=22 group=main
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.awt.EventQueue.getNextEvent(EventQueue.java:554)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:187)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"AWT-Shutdown" prio=5 id=21 group=system
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	at java.lang.Thread.run(Thread.java:748)

"AppKit Thread" daemon prio=5 id=11 group=system
   java.lang.Thread.State: RUNNABLE

"DestroyJavaVM" prio=5 id=26 group=main
   java.lang.Thread.State: RUNNABLE

"Dump Stack" prio=4 id=34 group=main
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:299)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

"Finalizer" daemon prio=8 id=3 group=system
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Java2D Disposer" daemon prio=10 id=17 group=system
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:748)

"Java2D Queue Flusher" daemon prio=10 id=15 group=system
   java.lang.Thread.State: TIMED_WAITING
	at java.lang.Object.wait(Native Method)
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:203)

"Reference Handler" daemon prio=10 id=2 group=system
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"SciJava-7645946a-Thread-2" prio=4 id=32 group=main
   java.lang.Thread.State: TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"SciJava-7645946a-Thread-3" prio=4 id=33 group=main
   java.lang.Thread.State: RUNNABLE
	at java.lang.Thread.dumpThreads(Native Method)
	at java.lang.Thread.getAllStackTraces(Thread.java:1610)
	at org.scijava.plugins.commands.debug.DumpStack.run(DumpStack.java:81)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Signal Dispatcher" daemon prio=9 id=4 group=system
   java.lang.Thread.State: RUNNABLE

"Timer-0" daemon prio=5 id=9 group=main
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)

"TimerQueue" daemon prio=5 id=30 group=system
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
	at javax.swing.TimerQueue.run(TimerQueue.java:174)
	at java.lang.Thread.run(Thread.java:748)
</pre>

And here's the exception in the console:

<pre>
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at java.net.URL.openStream(URL.java:1045)
	at net.imagej.legacy.plugin.MacroAutoCompletionProvider.parseFunctionsHtmlDoc(MacroAutoCompletionProvider.java:90)
	at net.imagej.legacy.plugin.MacroAutoCompletionProvider.<init>(MacroAutoCompletionProvider.java:67)
	at net.imagej.legacy.plugin.MacroAutoCompletionProvider.getInstance(MacroAutoCompletionProvider.java:79)
	at net.imagej.legacy.plugin.MacroLanguageSupportPlugin.getMacroAutoCompletionProvider(MacroLanguageSupportPlugin.java:97)
	at net.imagej.legacy.plugin.MacroLanguageSupportPlugin.getCompletionProvider(MacroLanguageSupportPlugin.java:91)
	at net.imagej.legacy.plugin.MacroLanguageSupportPlugin.install(MacroLanguageSupportPlugin.java:77)
	at org.scijava.ui.swing.script.EditorPane.setLanguage(EditorPane.java:518)
	at org.scijava.ui.swing.script.EditorPane.setLanguage(EditorPane.java:445)
	at org.scijava.ui.swing.script.EditorPane.setLanguageByFileName(EditorPane.java:433)
	at org.scijava.ui.swing.script.EditorPane.setFileName(EditorPane.java:379)
	at org.scijava.ui.swing.script.TextEditor.setEditorPaneFileName(TextEditor.java:1708)
	at org.scijava.ui.swing.script.TextEditor.open(TextEditor.java:1411)
	at net.imagej.legacy.plugin.DefaultLegacyEditor.open(DefaultLegacyEditor.java:92)
	at net.imagej.legacy.DefaultLegacyHooks.openInEditor(DefaultLegacyHooks.java:301)
	at ij.io.Opener.open(Opener.java)
	at ij.io.Opener.openAndAddToRecent(Opener.java:291)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:192)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:159)
	at java.lang.Thread.run(Thread.java:748)
</pre>

**Comment by ctrueden** [comment]
Aha, thanks @agclark12, very informative!

@haesleinhuepf It looks like an issue with the new macro autocompletion. Perhaps we should load the macro functions in the background rather than doing it lazily on demand? And maybe set a shorter timeout?

@agclark12 Are you behind some sort of firewall limiting outgoing traffic?

**Comment by haesleinhuepf** [comment]
Hey @ctrueden ,

thanks for the headsup! Actually, I was thinking of this server-connection already for some time. My internet at home is super slow and I always have to wait some seconds for this website to respond; whenever I open a macro...

Shall we remove the HTTP-request? The macro-auto-completion works nicely with the local copy...

Cheers,
Robert

**Comment by ctrueden** [comment]
@haesleinhuepf Yes, I think local-only is fine. We just have to remember to update the local copy with any snazzy new functions after they are added. I suppose we can rely on users for that, complaining about this-or-that function not being tab completed. 😉

**Comment by haesleinhuepf** [comment]
Alright, I'll prepare a PR tonight.

**Comment by agclark12** [comment]
@ctrueden yes, I was behind a firewall/proxy at work (though proxy settings in fiji are ok, since I can still update fiji from work). When i open an existing macro from home (i.e. no firewall), the script editor opens normally.

By the way, thanks for adding the macro autocompletion recently! It's super convenient. Any chance you guys would consider adding autocompletion for variables previously defined in the script?

**Comment by haesleinhuepf** [comment]
> Any chance you guys would consider adding autocompletion for variables previously defined in the script?

Hey @agclark12, that's an idea circulating in my head for some time. It's not super-easy to do, but it might come at some point... ;-)

**Comment by agclark12** [comment]
Well, looking forward to it if it does come! Thanks again for helping address this issue quickly!
