### ISSUE TITLE
NoSuchMethodError with updater

### ISSUE THREAD

**Issue by bgansemer** [fiji/fiji#233]
I've been receiving the following error when trying to run the updater (Help -> Update). Running version 1.52p on Windows 10 with Java 1.8.0_66.
```
[ERROR] Module threw error
java.lang.NoSuchMethodError: net.imagej.updater.util.AvailableSites.initializeAndAddSites(Lnet/imagej/updater/FilesCollection;Lorg/scijava/log/LogService;)V
	at net.imagej.ui.swing.updater.ImageJUpdater.run(ImageJUpdater.java:112)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Please let me know if you need any other information.

Thanks,
Ben

**Comment by ctrueden** [comment]
@frauzufall Any ideas?

**Comment by frauzufall** [comment]
Hi @bgansemer, 

sorry for not seeing this issue earlier! Maybe you already found the [forum post](https://forum.image.sc/t/imagej-fiji-is-improving-security/28609/), here is how to fix this:
- download [imagej-ui-swing-0.23.1](https://maven.scijava.org/service/local/repositories/releases/content/net/imagej/imagej-ui-swing/0.23.1/imagej-ui-swing-0.23.1.jar) and replace `Fiji.app/jars/imagej-ui-swing-0.22.0.jar` with it

After restarting Fiji, you should be able to update again. Sorry for the inconvenience. Please let me know if something still does not work!
