### ISSUE TITLE
Update site dependency shadowing Fiji dependency

### ISSUE THREAD

**Issue by spreka** [fiji/fiji#245]
Greetings.
I populated an update site with my plugin including its dependencies (mostly third-party jars and some default Fiji/ImageJ and Java-8 jars).  My problem is that I cannot properly shadow a certain default jar, namely *guava* with the guava.jar from nd4j my plugin requires to run.

Here's what I did:
I populated my custom update site with all the dependencies, resolved conflicting versions of some default jars by shadowing them in my update site which at the very least did not cause any instant errors on Fiji startup. Then I added this custom *org.nd4j.guava-1.0.0-beta6.jar* to my update site, finished updating/uploading successfully. However, on restart Fiji already threw some errors about not finding the class defnitions that I suppose were defined in the core guava.jar that I think is probably this one: *com.google.guava.guava-21.0.jar*.

The error I see on startup:
```
[ERROR] Cannot create plugin: class='net.imagej.mesh.io.stl.STLMeshIO', priority=0.0, enabled=true, pluginType=MeshIOPlugin
java.lang.NoClassDefFoundError: com/google/common/base/Strings
	at net.imagej.mesh.io.stl.STLMeshIO.<clinit>(STLMeshIO.java:63)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
	at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
	at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:226)
	at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:217)
	at org.scijava.plugin.AbstractSingletonService.initInstances(AbstractSingletonService.java:138)
	at org.scijava.plugin.AbstractSingletonService.getInstances(AbstractSingletonService.java:77)
	at org.scijava.plugin.SingletonService.lambda$initialize$0(SingletonService.java:97)
	at org.scijava.object.ObjectIndex.resolvePending(ObjectIndex.java:388)
	at org.scijava.object.ObjectIndex.get(ObjectIndex.java:133)
	at org.scijava.object.DefaultObjectService.getObjects(DefaultObjectService.java:87)
	at org.scijava.display.DefaultDisplayService.getDisplays(DefaultDisplayService.java:166)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:159)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:142)
	at org.scijava.AbstractGateway.launch(AbstractGateway.java:104)
	at net.imagej.Main.main(Main.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Strings
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

I am fairly certain I did not add this jar to my update site properly, so my question is how I could add this custom jar to the update site while maintaining the original, core version of the jar with the same name. Manually copying the 2 different jars to Fiji.app/jars/ folder doesn't produce any errors and my plugin also runs fine.

Any suggestion would be appreciated.

**Technical details:**
OS: Windows 10 version 1903
Java: Oracle jdk1.8
Fiji: downloaded from https://fiji.sc/

**Comment by ctrueden** [comment]
@spreka What is the URL for your update site? I'd like to inspect the JARs and `db.xml.gz` there.

**Comment by spreka** [comment]
@ctrueden Thanks for responding so quickly.
The update site is: https://sites.imagej.net/Spreka/

**Comment by ctrueden** [comment]
@spreka Thanks. I see `jars/guava-1.0.0-beta6.jar-20200312212004` on the update site, and looking in the `db.xml.gz` content, the ND4J version is definitely shadowing the core Guava library.

When you uploaded it from your local installation, how was it named on your local file system? `org.nd4j.guava-1.0.0-beta6.jar`? Or did you name it `guava-1.0.0-beta6.jar`?

* If you named it `guava-1.0.0-beta6.jar`, try using the longer name instead, since the Updater assumes anything named `guava-x.y.z-asdf.jar` (where x, y and z are numbers) means "the library called `guava` at version `x.y.z-asdf`." I.e. you can't upload two simultaneous versions of a thing called "guava."
* If you named it `org.nd4j.guava-1.0.0-beta6.jar`, then it appears the Updater renamed the file upon upload. This would surprise me, but it's not impossible, since the JAR file contains metadata about the original unshaded Guava library internally, which the ND4J project's shading process did not remove.

Once you confirm which scenario happened, we can dig further.

**Comment by spreka** [comment]
@ctrueden My local nd4j-originated guava jar was named `guava-1.0.0-beta6.jar`, I just copied the org.nd4j info from the pom. I will try renaming it to the full name in my local `/jars` folder.

**Comment by ctrueden** [comment]
@spreka Thanks for the info. The exact name is not important, as long as it does not clash with the existing `guava`. You could name it e.g. `nd4j-guava-1.0.0-beta6.jar`. I think this will work; please report back letting us know either way.

**Comment by spreka** [comment]
@ctrueden Thanks a lot for the support. I renamed it to `nd4j-guava-1.0.0-beta6.jar` as you suggested, unshadowed the previous version, updated this new to the update site and now Fiji starts without the google error while my plugins works as well.
Cheers!

**Comment by ctrueden** [comment]
@spreka Glad to hear it is working!
