### ISSUE TITLE
issues opening .lif series

### ISSUE THREAD

**Issue by juldub07** [fiji/fiji#259]
Trying to open .lif file series, but only the first one will open (even if another one is selected from the bioformat series option window), and exceptions are thrown (pasted below):

(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_202 [64-bit]; Mac OS X 10.15.6; 101MB of 10576MB (<1%)
 
java.lang.NoClassDefFoundError: org/apache/xml/serializer/TreeWalker
	at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:818)
	at loci.common.xml.XMLTools.writeXML(XMLTools.java:609)
	at loci.common.xml.XMLTools.writeXML(XMLTools.java:593)
	at loci.common.xml.XMLTools.dumpXML(XMLTools.java:293)
	at loci.common.xml.XMLTools.dumpXML(XMLTools.java:272)
	at ome.xml.meta.AbstractOMEXMLMetadata.dumpXML(AbstractOMEXMLMetadata.java:112)
	at ome.xml.meta.OMEXMLMetadataImpl.dumpXML(OMEXMLMetadataImpl.java:105)
	at loci.formats.ome.OMEPyramidStore.dumpXML(OMEPyramidStore.java:81)
	at loci.formats.services.OMEXMLServiceImpl.getOMEXML(OMEXMLServiceImpl.java:468)
	at loci.plugins.in.DisplayHandler.displayOMEXML(DisplayHandler.java:106)
	at loci.plugins.in.Importer.run(Importer.java:82)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:235)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.IJ.runPlugIn(IJ.java:187)
	at HandleExtraFileTypes.openImage(HandleExtraFileTypes.java:503)
	at HandleExtraFileTypes.run(HandleExtraFileTypes.java:76)
	at ij.IJ.runUserPlugIn(IJ.java:235)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.IJ.runPlugIn(IJ.java:187)
	at ij.io.Opener.openWithHandleExtraFileTypes(Opener.java:512)
	at ij.io.Opener.openUsingHandleExtraFileTypes(Opener.java:369)
	at ij.io.Opener.openImage(Opener.java:359)
	at ij.io.Opener.openImage(Opener.java:243)
	at ij.io.Opener.open(Opener.java:109)
	at ij.io.Opener.openAndAddToRecent(Opener.java:292)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:194)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:160)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.serializer.TreeWalker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more

**Comment by imagejan** [comment]
This issue is caused by the latest Fiji updates. On some systems, the updater was not installing the file `serializer-2.7.2.jar` that is required by the updater.

Please see [this discussion](https://forum.image.sc/t/java-lang-noclassdeffounderror-org-apache-xml-serializer-treewalker/41205/5?u=imagejan) on the forum, you'll need to put `serializer-2.7.2.jar` in your `Fiji.app/jars/` folder, then restart Fiji and run the updater again.

Could you please also tell us the exact time when you last updated Fiji? I'm asking because the updater issue appears to have been present since Saturday, but should have been fixed since Monday evening. So if you updated later and got that error, this means the issue is not yet fixed.

**Comment by juldub07** [comment]
@imagejan I updated FIJI Monday morning, so that may explain it. Will get the serializer file. Thanks for the help!!
