### ISSUE TITLE
"Invalid service" error on Fiji startup (FilamentDetector)

### ISSUE THREAD

**Issue by bogovicj** [fiji/fiji#273]
I observe the error below when starting Fiji.  Fiji does open successfully, and I don't experience any other issues, but didn't look very hard.

```
➜  Fiji.app ./Contents/MacOS/ImageJ-macosx       
[ERROR] Invalid service: sc.fiji.filamentdetector.gui.GUIStatusService
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at org.scijava.util.ClassUtils.getAnnotatedFields(ClassUtils.java:193)
	at org.scijava.util.ClassUtils.getAnnotatedFields(ClassUtils.java:163)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:315)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
[ERROR] No match: sc.fiji.filamentdetector.gui.GUIStatusService
```

I also reported it here: https://github.com/fiji/FilamentDetector/issues/24
and @acardona describes this issue here: https://forum.image.sc/t/fiji-fails-to-launch-after-update/44582

**Comment by ctrueden** [comment]
It's been a long time, but this is certainly fixed now. Maybe by scijava/scijava-common#422 if I am tracing the issue linkages correctly.
