### ISSUE TITLE
Cannot import javax.vecmath when running python script

### ISSUE THREAD

**Issue by phsamuel** [fiji/fiji#312]
Hi, I try to go through the tutorial at [Fiji Programming Tutorial](https://syn.mrc-lmb.cam.ac.uk/acardona/fiji-tutorial/)

I tried one simple example like the following

```
# Load an image of the Drosophila larval fly brain and segment  
# the 5-micron diameter cells present in the red channel.  
  
from script.imglib.analysis import DoGPeaks  
from script.imglib.color import Red  
from script.imglib.algorithm import Scale2D  
from script.imglib.math import Compute  
from script.imglib import ImgLib  
from ij3d import Image3DUniverse  
from javax.vecmath import Color3f, Point3f  
from ij import IJ  
  
cell_diameter = 5  # in microns  
minPeak = 40 # The minimum intensity for a peak to be considered so.  
imp = IJ.openImage("http://samples.fiji.sc//samples/first-instar-brain.zip")  
  
# Scale the X,Y axis down to isotropy with the Z axis  
cal = imp.getCalibration()  
scale2D = cal.pixelWidth / cal.pixelDepth  
iso = Compute.inFloats(Scale2D(Red(ImgLib.wrap(imp)), scale2D))  
  
# Find peaks by difference of Gaussian  
sigma = (cell_diameter  / cal.pixelWidth) * scale2D  
peaks = DoGPeaks(iso, sigma, sigma * 0.5, minPeak, 1)  
print "Found", len(peaks), "peaks"  
  
# Convert the peaks into points in calibrated image space  
ps = []  
for peak in peaks:  
  p = Point3f(peak)  
  p.scale(cal.pixelWidth * 1/scale2D)  
  ps.append(p)  
  
# Show the peaks as spheres in 3D, along with orthoslices:  
univ = Image3DUniverse(512, 512)  
univ.addIcospheres(ps, Color3f(1, 0, 0), 2, cell_diameter/2, "Cells").setLocked(True)  
univ.addOrthoslice(imp).setLocked(True)  
univ.show()
```

However, it seems that Fiji is unable to find the package javax.vecmath. Moreover, it seems to complain .ImageJ_3D_Viewer.props is missing in my home folder. The OS I am using is Ubuntu 20.04 and using the one with JRE included. 

The error message I got is as follows
```
Started imglib.py at Mon Jul 25 20:33:09 CDT 2022
Traceback (most recent call last):
  File "/home/phsamuel/Dropbox/code/fiji/imglib.py", line 7, in <module>
    from javax.vecmath import Color3f, Point3f  
ImportError: No module named vecmath

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.import_logic(imp.java:1290)
	at org.python.core.imp.import_module_level(imp.java:1369)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at org.python.pycode._pyx0.f$0(/home/phsamuel/Dropbox/code/fiji/imglib.py:35)
	at org.python.pycode._pyx0.call_function(/home/phsamuel/Dropbox/code/fiji/imglib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
and the console shows

```
3D [dev] 1.6.0-scijava-2-pre11-daily-experimental daily

/home/phsamuel/.ImageJ_3D_Viewer.props (No such file or directory)
```

Thanks ahead!

**Comment by imagejan** [comment]
As far as I can tell, Fiji ships a shadowed version of vecmath under the package name `org.scijava.vecmath` since quite a while.

This should work:
```python
from org.scijava.vecmath import Color3f, Point3f
```

Maybe it can be corrected in the tutorials (@acardona)?

---

```
/home/phsamuel/.ImageJ_3D_Viewer.props (No such file or directory)
```

I don't know, this might be unrelated.

**Comment by ctrueden** [comment]
> Maybe it can be corrected in the tutorials (@acardona)?

Agreed. And even better would be to migrate those tutorials to the ImageJ wiki at imagej.net so that the community can help maintain them.

**Comment by ctrueden** [comment]
@phsamuel Using `from org.scijava.vecmath import Color3f, Point3f` should work, but if not, please feel free to reopen the issue with details of what goes wrong!

**Comment by phsamuel** [comment]
It seems like the tutorial still will not work as "
http://samples.fiji.sc//samples/first-instar-brain.zip" no longer exists.

I think the tutorial is very nice. I wonder if there is any script tutorial
in "imagej.net". And is that we can't use numpy/scipy in fiji scripting?

Thanks!
Sam

**Comment by imagejan** [comment]
> `http://samples.fiji.sc//samples/first-instar-brain.zip` no longer exists.

It seems this moved to:

```
https://samples.fiji.sc/first-instar-brain.zip
```

**Comment by acardona** [comment]
Thanks, the link to https://samples.fiji.sc/first-instar-brain.zip is now correct in the Fiji Python Tutorial.

**Comment by ctrueden** [comment]
Thanks @acardona. I also added a redirect from `https://samples.fiji.sc/samples/<...>` to `https://samples.fiji.sc/<...>`, so that any other such URLs still in the wild will continue to function.
