### ISSUE TITLE
Fiji fails to build using maven

### ISSUE THREAD

**Issue by kbipinkumar** [fiji/fiji#316]
I am trying to build fiji using maven in the hopes of it can be packged for third party [Archlinux repo](https://github.com/BioArchLinux) maintained by volunteers. the objective is that if the build process can complete successfully and reproducibly Fiji can be added to repo.

However, maven is exiting with the errors below. Any help will be appreciated. 

[surefire-reports.zip](https://github.com/fiji/fiji/files/10268101/surefire-reports.zip)

```
-------------------------------------------------------------------------------
Test set: sc.fiji.InitializationTest
------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.035 s <<< FAILURE! - in sc.fiji.InitializationTest
testInitialization(sc.fiji.InitializationTest)  Time elapsed: 2.977 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid service: sc.fiji.filamentdetector.overlay.DefaultColorService
	at sc.fiji.InitializationTest.testInitialization(InitializationTest.java:38)
Caused by: java.lang.NullPointerException: Cannot invoke "org.scijava.table.Column.size()" because "column" is null
	at sc.fiji.InitializationTest.testInitialization(InitializationTest.java:38)
```

**Comment by hinerm** [comment]
@kbipinkumar what version of Java are you using? In your `.dumpstream` is a:
```
 Unsupported class file major version 63
```

so I'm assuming you're using [Java 19](https://stackabuse.com/bytes/fix-java-error-unsupported-class-file-major-version-63/)?

If so, I'd recommend trying to recompile with Java 8. if you're still getting compilation problems with Java 8, let us know!

**Comment by Kiri2002** [comment]
@hinerm I successfully built FIJI in jdk8-openjdk using maven, But I only get fiji-2.15.1.jar and some folders in target.

How can I get the missing files(executive-bin etc. ) to get a fully usable FIJI ?

**Comment by ctrueden** [comment]
@Kiri2002 I wrote some details in [this comment](https://github.com/fiji/fiji/issues/311#issuecomment-2108890368) about how the Fiji distribution is structured. The downloadable Fiji application is assembled from the JAR file built here, its dependencies (also JAR files), and various non-JAR resources, many but not all of which are committed to the repository here, but not part of the Maven build process per se.

About packaging Fiji for Arch: I suggest you read through imagej/imagej2#162, where packaging Fiji/ImageJ for Gentoo was discussed in some detail. You are going to have a lot of the same considerations and issues when it comes to Arch, I'm sure. I'm happy to discuss more here, if you have questions.
