### ISSUE TITLE
Beanshell Interprete incompatible with Java 8?

### ISSUE THREAD

**Issue by axtimwalde** [fiji/fiji#322]
I cannot run Fiji with
```
fiji shift-stack.bsh
```
currently, because it fails with
```
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
java.lang.UnsupportedClassVersionError: bsh/Interpreter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:252)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:87)
```
but I can run the same Beanshell script in the Script Editor.  Any clues?

**Comment by axtimwalde** [comment]
@ctrueden, is it possible that the executable uses a different `bsh-...jar`? [This script](https://github.com/fiji/fiji/blob/master/bin/find-jar-for-class.bsh) run from the script editor prints
`Class void is in /home/saalfeld/packages/Fiji.app/jars/bsh-2.1.0.jar` as expected.  It also runs Beanshell script successfully.

```
classLoader = ClassLoader.getSystemClassLoader();
slashed = "bsh/Interpreter.class";
try {
	jars = classLoader.getResources(slashed);
	if (!jars.hasMoreElements()) {
		throw new RuntimeException("Not found??? " + c);
	}
	while (jars.hasMoreElements()) {
		jar = jars.nextElement().toString();
		if (jar.startsWith("jar:file:")) {
			jar = jar.substring(9);
		}
		exclamation = jar.indexOf("!/");
		if (exclamation >= 0) {
			jar = jar.substring(0, exclamation);
		}
		print("Class " + c + " is in " + jar);
	}
} catch (Exception e) {
	print("Class " + c + " was not found in the classpath");
}
```
