### ISSUE TITLE
Unrecognized command "Table Action"

### ISSUE THREAD

**Issue by thorstenwagner** [fiji/fiji#323]
I downloaded a fresh fiji version:
![grafik](https://user-images.githubusercontent.com/1113977/235436588-a0694f61-ed80-4bf4-886f-37c444e2d90a.png)

Then I did the following
```
run("Blobs (25K)");
setAutoThreshold("Default dark no-reset");
setOption("BlackBackground", true);
run("Convert to Mask");
run("Invert");
run("Analyze Particles...", "display clear");
```

If you now click twice on on a results table row you see this exception:

```
Exception in thread "Run$_AWT-EventQueue-0" java.lang.RuntimeException: Macro canceled
	at ij.IJ.abort(IJ.java:2484)
	at ij.IJ.testAbort(IJ.java:423)
	at ij.IJ.run(IJ.java:322)
	at ij.text.TextPanel.mouseClicked(TextPanel.java:441)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by thorstenwagner** [comment]
Upgrading to the latest Imagej (1.54d) solves the problem.
