### ISSUE TITLE
Null pointer exception when opening macro editor

### ISSUE THREAD

**Issue by MartinSalinas98** [fiji/fiji#326]
# System settings
Note: I'm not entirely sure about how useful are some of them, but I'd rather provide extra unnecessary info instead of less of the required.
- **Distro and version:** Ubuntu 22.04
- **gcc/g++ version:** 10.4.0
- **Fiji version (obtained from fiji GUI):** (Fiji is Just) Imagej 2.9.0/1.53t / Java 1.8.0_322 (64-bit)
# Steps to reproduce the error
- Go to Plugins -> Macros -> Record...
- Type anything inside the text box
- Click "Create"
# The error
A new window pops up with this message:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.scijava.ui.swing.script.FileSystemTree$DirectoryWatcher.<init>(FileSystemTree.java:513)
	at org.scijava.ui.swing.script.FileSystemTree.<init>(FileSystemTree.java:261)
	at org.scijava.ui.swing.script.TextEditor.<init>(TextEditor.java:324)
	at net.imagej.legacy.plugin.DefaultLegacyEditor$1.<init>(DefaultLegacyEditor.java:62)
	at net.imagej.legacy.plugin.DefaultLegacyEditor.editor(DefaultLegacyEditor.java:62)
	at net.imagej.legacy.plugin.DefaultLegacyEditor.create(DefaultLegacyEditor.java:96)
	at net.imagej.legacy.DefaultLegacyHooks.createInEditor(DefaultLegacyHooks.java:317)
	at ij.plugin.frame.Recorder.createMacro(Recorder.java:762)
	at ij.plugin.frame.Recorder.actionPerformed(Recorder.java:809)
	at java.awt.Button.processActionEvent(Button.java:409)
	at java.awt.Button.processEvent(Button.java:377)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
The window in question looks like this (just in case it is a specific type of window that pops up in certain cases that might help narrow the origin of the error).
![Screenshot from 2023-07-05 16-22-21](https://github.com/fiji/fiji/assets/23634297/90fc9368-4a66-4db6-af38-dab47abdf301)
# Further things I found out about this error
- If I reset the configuration going to Edit -> Options -> Reset..., then restart fiji, the problem looks like it's gone, but only for a while, it ends up happening again after some time.
- Digging deeper into that, I found out that the reset option actually what it does is delete an ImageJ settings file located in `~/.imagej` called `IJ_Prefs.txt`, so, yeah, manually deleting such file has exactly the same effect that using the reset option. But this does not solve the problem permanently, as it ends up coming back at some point.
- Analyzing the contents of that file, comparing a version of it where the error did not appear with one that did, I found a specific line that was the one causing the issue: `div-by-zero=Infinity`. When deleting that line, the error disappeared. But again, only temporarily, and sometimes, deppending on the contents of that file, ImageJ writes that line back inmediately after restarting Fiji.
- I do not know yet when and why is Fiji writing that line on the file, and why is that causing a Null Pointer Exception when recording macros, but I think that's a pretty good starting point for someone with a deeper understanding of Fiji to be able to take it from there.
# Config file
Just in case it is useful too, here is my full config file:
```
#ImageJ 1.53t Preferences
#Wed Jul 05 16:26:45 CEST 2023
.recent.command19=Close
.recent.command18=Close
.recent.command17=Close
new.width=512
.recent.command16=Open...
.recent.command15=Close
.recent.command14=Close
pp.height=340
.recent.command13=Close
.recent.command12=Close
.recent.command11=Close
.recent.command10=Open...
.bioformats.ungroupFiles=false
.recent.command9=Open...
plugin00=h,"*recent commands[9]",fiji.util.Recent_Commands
.recent.command8=Close
.recent.command7=Open...
.recent.command6=Brightness/Contrast...
.recent.command5=Open...
.recent.command4=Open...
.recent.command3=Close
.recent.command2=Select Next Lane
.recent.command1=Text Window
.recent.command0=Close
.bioformats.showMetadata=false
pp.options=0
bcolor=\#000000
noise.sd=25.0
new.fill=1
raw.width=512
fcolor=\#FFFFFF
.bioformats.windowless=false
.debug.loc=1200,188
.avi.reader.path=/home/jconesa/RUSKA_MOUNTPOINT/20221107_VideosCORR/aT13_new13_CTR.avi
.bioformats.showOMEXML=false
.bs.background=true
raw.gap=0
prefs.options=12599312
.b&c.loc=1402,54
raw.n=1
.log.height=250
.log.width=400
measurements=19
.bioformats.openAllSeries=false
.bioformats.stackFormat=Hyperstack
.recent.command99=Close
.recent.command98=Close
.recent.command97=Close
.recent.command96=Close
.recent.command95=Close
.bioformats.autoscale=true
.recent.command94=Close
.recent.command93=Close
.recent.command92=System Clipboard
.recent.command91=Select Next Lane
.recent.command90=Text Window
.bioformats.virtual=false
.bioformats.groupFiles=false
.recent.command.lastIndex=38
.bioformats.mustGroup=false
.recent.command89=Close
.recent.command88=Close
.recent.command87=Start Animation [\\]
.bioformats.specifyRanges=false
.bioformats.colorMode=Default
.recent.command86=Start Animation [\\]
.recent.command85=Start Animation [\\]
.recent.command84=Start Animation [\\]
.recent.command83=Start Animation [\\]
.recent.command82=Start Animation [\\]
.recent.command81=Brightness/Contrast...
.recent.command80=Close
jpeg=85
.bioformats.concatenate=false
.recent.command79=Close
.recent.command78=Close
dir.image=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VSTCC/Training stack/
.recent.command77=Brightness/Contrast...
.recent.command76=Close
.recent.command75=Close
.recent.command74=Brightness/Contrast...
.recent.command73=Tiff...
new.height=512
.recent.command72=Images to Stack
.recent.command71=Close
.recent.command70=Image Sequence... 
.zproject.method=3
raw.offset=0
.bioformats.stackOrder=XYCZT
precision=3
.recent.command69=Image Sequence... 
new.slices=1
.recent.command68=Tiff...
.recent.command67=Close
.recent.command66=Close
.recent.command65=Close
.recent.command64=Close
.recent.command63=Close
.recent.command62=Copy to System
.recent.command61=Select All
.recent.command60=Brightness/Contrast...
raw.height=512
.bioformats.swapDimensions=false
ap.options=64
.threshold.no-reset=true
.recent.command59=Open...
.recent.command58=Open...
.recent.command57=Save
.recent.command56=Duplicate...
.recent.command55=Brightness/Contrast...
.recent.command54=Open...
pp.width=600
.recent.command53=Tiff...
.recent.command52=Close
.log.loc=333,253
.recent.command51=Open...
fps=7.0
.recent.command50=Tiff...
raw.options=0
new.type=0
recent14=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/GFP1STCCGFP1STCC05_tophat.tif
recent13=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/GFP1STCCGFP1STCC06_tophat.tif
recent12=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/GFP1STCCGFP1STCC07_tophat.tif
recent11=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/GFP1STCCGFP1STCC08_tophat.tif
ij.y=127
showcolor=\#00FFFF
recent10=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/GFP1STCCGFP1STCC09_tophat.tif
ij.x=1280
roicolor=\#FFFF00
.save.sequence.dir=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/
.recent.command49=Duplicate...
.recent.command48=Close
.recent.command47=Tiff...
.recent.command46=Close
.recent.command45=Tiff...
.recent.command44=Close
.recent.command43=Tiff...
.recent.command42=Close
.recent.command41=Tiff...
.toolbar.tool04=LUT Menu Tool
.recent.command40=Close
.bioformats.firstTime=false
.bioformats.showROIs=false
recent09=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/GFP1STCCGFP1STCC10_tophat.tif
recent08=/home/jconesa/data/JOlivares/Processing/JOlivares/Charge/GFP1STCC/GFP1STCCGFP1STCC11_tophat.tif
recent07=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VSTCC/Trining STCC/GFP1STCCGFP1STCC01_tophat.tif
recent06=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VSTCC/Trining STCC/GFP1STCC_tophat.tif
recent05=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VO/GFP1O/Trainingstack/GFP1OTraining.tif
recent04=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VST/GFP1ST/Training Stack/GFP1Aligned267of267_600_10px-1.tif
.bioformats.crop=false
recent03=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VO/GFP1O/Trainingstack/1.5.tif
recent02=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VO/GFP1O/Trainingstack/5.20
recent01=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VO/GFP1O/Trainingstack/15.100
recent00=/home/jconesa/data/JOlivares/Processing/JOlivares/N2VSTCC/Training stack/GFP1STCC_tophat.tif
.recent.command39=Tiff...
.recent.command38=Close
.threshold.mode=0
.recent.command37=Quit
.recent.command36=Quit
.threshold.loc=1468,499
.recent.command35=Record...
.bioformats.splitFocalPlanes=false
.recent.command34=Quit
.recent.command33=Close
.recent.command32=Close
.recent.command31=Close
.recent.command30=Close
.bioformats.stitchTiles=false
.threshold.dark=true
div-by-zero=Infinity
.threshold.raw=false
.bioformats.roiMode=ROI manager
menu.size=0
.bioformats.upgradeCheck=false
pp.fontsize=14
.recent.command29=Close
.recent.command28=Close
.recent.command27=Close
.recent.command26=Close
.recent.command25=Close
.recent.command24=Close
.recent.command23=Close
.recent.command22=Close
.bioformats.splitTimepoints=false
.recent.command21=Close
.recent.command20=Close
raw.type=0
.bioformats.splitWindows=false
.resizer.zero=false
prefs.options2=2
```
I hope you find this useful in order to solve this issue.

**Comment by MartinSalinas98** [comment]
Hi @ctrueden. Thank you for your quick response and help!

> About the Edit → Options → Reset...: if that actually does clear up the problem temporarily, that is even weirder. Is it possible this is a red herring? I.e. that the behavior is simply non-deterministic, where you sometimes see it, and sometimes don't, regardless of whether the prefs have been cleared recently? Does the error really happen every time until the prefs are cleared?
#### I have tried the following process:
- Remove the preferences file (`rm ~/.imagej/IJ_Prefs.txt`), and then launch Fiji. The program runs fine.
- Restore the confilctive file (`cp ~/IJ_Prefs_bad.txt ~/.imagej/IJ_Prefs.txt`) and launch Fiji. The problem shows up again.

Did the above steps 10 times in a row, with exactly the same results each time, so I guess it has to be deterministic.

Funny enough, I am unable to open the script editor. I go to File -> New -> Script..., but a window pops up with this trace:
```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_322 [64-bit]; Linux 5.15.0-58-generic; 130MB of 400000MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.scijava.ui.swing.script.FileSystemTree$DirectoryWatcher.<init>(FileSystemTree.java:513)
	at org.scijava.ui.swing.script.FileSystemTree.<init>(FileSystemTree.java:261)
	at org.scijava.ui.swing.script.TextEditor.<init>(TextEditor.java:324)
	at org.scijava.ui.swing.script.ScriptEditor.run(ScriptEditor.java:53)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```
This is the window that shows up with the exception (just in case it provides any additional info):
![image](https://github.com/fiji/fiji/assets/23634297/6421e4e3-ca25-42f9-b74f-7635519b7762)
This happens regardless of the preferences file's contents, it does not matter if I remove it or if I restore the problematic one.

**Comment by MartinSalinas98** [comment]
Hey @ctrueden, is there any update on this? Thanks!
