### ISSUE TITLE
search bar errors

### ISSUE THREAD

**Issue by martinschorb** [fiji/fiji#327]
Hi,

when typing in the search bar and no results are found, an error is thrown in the results page.

![image](https://github.com/fiji/fiji/assets/35071867/b3eac5a2-17f7-4231-904e-566ccdba59d2)

```

java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at org.scijava.search.classes.ClassesSearcher.startsWith(ClassesSearcher.java:139)
	at org.scijava.search.classes.ClassesSearcher.lambda$search$0(ClassesSearcher.java:82)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.scijava.search.classes.ClassesSearcher.search(ClassesSearcher.java:83)
	at org.scijava.search.DefaultSearchOperation$SearchAttempt.run(DefaultSearchOperation.java:181)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:233)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

This is a brand new Fiji linux64. To reproduce:

- open Fiji
- search for `qq`

**Comment by ctrueden** [comment]
Thanks for the report, @martinschorb. As a workaround for the moment, you can uncheck the box next to the "Classes" header in the search results window, and it will not try searching Java classes for your query, which should avoid the error.
