### ISSUE TITLE
Fiji doesn't quit when killed from console on Windows

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji#347]
`ctrl` + `c` from the terminal on Windows 11 results in the following deadlock:

```
"Thread-3" #22 prio=5 os_prio=0 tid=0x0000000034825000 nid=0x3f60 in Object.wait() [0x000000003f03e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
        - locked <0x000000034cc82260> (a java.awt.EventQueue$1AWTInvocationLock)
        at java.awt.Window.doDispose(Window.java:1210)
        at java.awt.Window.dispose(Window.java:1147)
        at ij.ImageJ.run(ImageJ.java:867)
        at net.imagej.legacy.IJ1Helper.dispose(IJ1Helper.java:258)
        - locked <0x000000034d4572f8> (a net.imagej.legacy.IJ1Helper)
        at net.imagej.legacy.ui.LegacyUI.dispose(LegacyUI.java:125)
        at org.scijava.ui.DefaultUIService.dispose(DefaultUIService.java:373)
        - locked <0x00000003713e33f8> (a org.scijava.ui.DefaultUIService)
        at org.scijava.Context.doDispose(Context.java:597)
        - locked <0x00000003707bffa8> (a org.scijava.Context)
        at org.scijava.Context.lambda$new$0(Context.java:295)
        at org.scijava.Context$$Lambda$67/1994085390.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)


"AWT-EventQueue-0" #17 prio=6 os_prio=0 tid=0x000000003137c800 nid=0xb28 runnable [0x000000003f61d000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WComponentPeer.hide(Native Method)
        - locked <0x0000000346e2ba40> (a sun.awt.windows.WFramePeer)
        at sun.awt.windows.WWindowPeer.hide(WWindowPeer.java:327)
        at sun.awt.windows.WComponentPeer.setVisible(WComponentPeer.java:125)
        at java.awt.Component.hide(Component.java:1708)
        - locked <0x000000034d463248> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.hide(Window.java:1115)
        at java.awt.Window$1DisposeAction.run(Window.java:1188)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

In a mingw, the console locks up and we are never returned to the prompt. From the command prompt running with `--console`, we do go back to the prompt but an orphaned JVM is kept running now in the background.

**Comment by hinerm** [comment]
I'm not sure how to debug this further. I tried modifying this bit to run on the EDT:

```
- locked <0x000000034cc82260> (a java.awt.EventQueue$1AWTInvocationLock)
at java.awt.Window.doDispose(Window.java:1210)
at java.awt.Window.dispose(Window.java:1147)
at ij.ImageJ.run(ImageJ.java:867)
at net.imagej.legacy.IJ1Helper.dispose(IJ1Helper.java:258)
```
🔽
```
- locked <0x00000003483ca040> (a java.awt.EventQueue$1AWTInvocationLock)
at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
at net.imagej.legacy.IJ1Helper.dispose(IJ1Helper.java:265)
```

But no change. None of the Java object locks appear multiple times in the stack trace so I assume the deadlock is happening in the native code.

**Comment by hinerm** [comment]
Coming back to this because of https://github.com/fiji/fiji/issues/375

I currently have [a branch](https://github.com/imagej/imagej-legacy/tree/windows-deadlock) where I'm trying to solve this.

It's unclear if [this `IJ1Helper.dispose` logic](https://github.com/imagej/imagej-legacy/blob/c24d491123dc3d3e1ee484e7b3a1833ada83ec7a/src/main/java/net/imagej/legacy/IJ1Helper.java#L245-L255) ever worked on windows, since it is rarely encountered as [this check](https://github.com/imagej/imagej-legacy/blob/c24d491123dc3d3e1ee484e7b3a1833ada83ec7a/src/main/java/net/imagej/legacy/IJ1Helper.java#L243) will be true under normal shutdown mechanisms (clicking the `X`).

I tried simply wrapping all the `dispose` actions in [`EventQueue.invokeLater`](https://github.com/imagej/imagej-legacy/blob/76151c21275945c5d2921f6f10330b1d98b97f15/src/main/java/net/imagej/legacy/IJ1Helper.java#L264). Doing that I can actually quit with `Ctrl + C`! AND the update works!! ... However it's a messy shutdown, e.g. [this message](https://github.com/imagej/imagej-legacy/blob/76151c21275945c5d2921f6f10330b1d98b97f15/src/main/java/net/imagej/legacy/IJ1Helper.java#L255) never prints, indicating the EDT is still deadlocked.

I tried a DIY [`invokeAndWait`](https://github.com/imagej/imagej-legacy/blob/76151c21275945c5d2921f6f10330b1d98b97f15/src/main/java/net/imagej/legacy/IJ1Helper.java#L267-L269) (because `invokeLater` does acquire an `AWTInvocationLock` lock and I wanted to be sure that wasn't deadlocking) to see what was going on.

When closing via `ctrl+c` the deadlock is:
![image](https://github.com/user-attachments/assets/212f1dc1-346c-4bf1-818e-0d1ee32971dc)

When closing via `System.exit(0)`, as in the Fiji migration, the deadlock is slightly different:
![image](https://github.com/user-attachments/assets/c95fa6d8-4e7e-4c35-a61c-896092627633)

**Comment by hinerm** [comment]
FWIW, removing the [shutdown hook](https://github.com/scijava/scijava-common/blob/1b25c5802e42d1061645b3597c18242cfda3b879/src/main/java/org/scijava/Context.java#L316) allows `ctrl + c` to work on Windows and doesn't seem to interfere with the Jaunch Fiji upgrade process nor `napari-imagej`, so simply disabling the hook on Windows seems reasonable?

**Comment by ctrueden** [comment]
I'm in favor of not adding the hook on Windows, for now. Ideally we'd figure out how to make it work on Windows of course, but in practice, if Windows works better without it, while Linux and macOS work better with it present, then let's just do it that way. And clearly document the huge hack as a code comment.
