### ISSUE TITLE
Fiji Future: Missing `vecmath` module

### ISSUE THREAD

**Issue by elevans** [fiji/fiji#371]
I have a script to view imglib2 meshes with the 3Ds viewer. It uses `org.scijava.vecmath.Point3f`. When trying to run the script I get an `ImportError` due to a missing module:

```python
Traceback (most recent call last):
  File "New_.py", line 1, in <module>
ImportError: No module named vecmath

	at org.python.core.Py.ImportError(Py.java:327)
	at org.python.core.imp.import_logic(imp.java:1292)
	at org.python.core.imp.import_module_level(imp.java:1371)
	at org.python.core.imp.importName(imp.java:1544)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1636)
	at org.python.core.imp.importFrom(imp.java:1611)
	at org.python.pycode._pyx2.f$0(New_.py:1)
	at org.python.pycode._pyx2.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1742)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ctrueden** [comment]
Can you try changing it to `org.jogamp.vecmath.Point3f`?
