### ISSUE TITLE
Fiji doesn't quit after upgrading

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji#375]
On Windows, when I take a `Fiji.app` and manually prepare it for upgrade by:

1. Adding the scijava `app-launcher.jar`
2. Updating the `imagej-ui-swing.jar`
3. Adding the `fiji.toml` from `fiji/fiji`
4. Adding the other `*.toml` files + launcher from `apposed/jaunch`
5. Run `Help > Update...` and affirming that I want to update

Fiji closes after performing the update. However it looks like it hits an ImageJ legacy disposal deadlock (Stack trace below). Closing through normal means is fine.

```
"RMI TCP Connection(2)-10.130.188.246" #44 daemon prio=5 os_prio=0 tid=0x000000002c91e800 nid=0x1f50 runnable [0x0000000036e7e000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        - locked <0x0000000350561288> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:555)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$201/1492268668.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - <0x00000003500d41c0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"JMX server connection timeout 43" #43 daemon prio=5 os_prio=0 tid=0x000000002c91d800 nid=0x25f4 in Object.wait() [0x00000000434af000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at com.sun.jmx.remote.internal.ServerCommunicatorAdmin$Timeout.run(ServerCommunicatorAdmin.java:168)
        - locked <0x00000003501bbd88> (a [I)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"RMI Scheduler(0)" #42 daemon prio=5 os_prio=0 tid=0x000000002c91d000 nid=0x7a48 waiting on condition [0x0000000042eaf000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000035006ae80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2083)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"RMI TCP Connection(1)-10.130.188.246" #41 daemon prio=5 os_prio=0 tid=0x000000002c916800 nid=0xe10 runnable [0x000000003ce7e000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        - locked <0x00000003501507d8> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:555)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$201/1492268668.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - <0x00000003500cf1f8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"RMI TCP Accept-0" #40 daemon prio=5 os_prio=0 tid=0x000000002c918000 nid=0x5360 runnable [0x000000003607f000]
   java.lang.Thread.State: RUNNABLE
        at java.net.DualStackPlainSocketImpl.accept0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
        - locked <0x00000003500713b0> (a java.net.SocksSocketImpl)
        at java.net.ServerSocket.implAccept(ServerSocket.java:571)
        at java.net.ServerSocket.accept(ServerSocket.java:534)
        at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"Thread-3" #22 prio=5 os_prio=0 tid=0x000000002c915000 nid=0x44c8 in Object.wait() [0x00000000432af000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
        - locked <0x000000034fe2c920> (a java.awt.EventQueue$1AWTInvocationLock)
        at java.awt.Window.doDispose(Window.java:1210)
        at java.awt.Window.dispose(Window.java:1147)
        at ij.ImageJ.run(ImageJ.java:867)
        at net.imagej.legacy.IJ1Helper.dispose(IJ1Helper.java:258)
        - locked <0x0000000377339148> (a net.imagej.legacy.IJ1Helper)
        at net.imagej.legacy.ui.LegacyUI.dispose(LegacyUI.java:125)
        at org.scijava.ui.DefaultUIService.dispose(DefaultUIService.java:373)
        - locked <0x00000003751a5e28> (a org.scijava.ui.DefaultUIService)
        at org.scijava.Context.doDispose(Context.java:597)
        - locked <0x00000003749c0640> (a org.scijava.Context)
        at org.scijava.Context.lambda$new$0(Context.java:295)
        at org.scijava.Context$$Lambda$74/1547994163.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"pool-3-thread-1" #38 prio=5 os_prio=0 tid=0x000000002c915800 nid=0x80a4 waiting on condition [0x00000000430af000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000034e92fc60> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"SciJava-549621f3-Thread-1" #30 daemon prio=5 os_prio=0 tid=0x000000002c7c4800 nid=0x42e0 waiting on condition [0x000000003da5f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000037511ac18> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"Update..." #29 prio=4 os_prio=-1 tid=0x000000002c7c3800 nid=0x7b84 waiting on condition [0x000000003d85f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000377a89ad0> (a java.util.concurrent.FutureTask)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
        at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
        at ij.IJ.runPlugIn(IJ.java)
        at ij.Executer.runCommand(Executer.java:152)
        at ij.Executer.run(Executer.java:70)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"DestroyJavaVM" #28 prio=5 os_prio=0 tid=0x000000002c7ca000 nid=0x4dc4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"MarlinRenderer Disposer" #26 daemon prio=10 os_prio=2 tid=0x000000002c7c7800 nid=0x5f90 in Object.wait() [0x000000003d25f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000377b499f8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x0000000377b499f8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at sun.java2d.marlin.OffHeapArray$OffHeapDisposer.run(OffHeapArray.java:154)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"TimerQueue" #24 daemon prio=5 os_prio=0 tid=0x00000000345cd800 nid=0x5ed8 waiting on condition [0x000000003fe3f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000377b80c50> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
        at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
        at javax.swing.TimerQueue.run(TimerQueue.java:174)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - <0x0000000377ed31b0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"AWT-EventQueue-0" #17 prio=6 os_prio=0 tid=0x000000003342b800 nid=0x66d0 runnable [0x000000003de5d000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WComponentPeer.hide(Native Method)
        - locked <0x000000037755a9f8> (a sun.awt.windows.WFramePeer)
        at sun.awt.windows.WWindowPeer.hide(WWindowPeer.java:327)
        at sun.awt.windows.WComponentPeer.setVisible(WComponentPeer.java:125)
        at java.awt.Component.hide(Component.java:1708)
        - locked <0x00000003774da250> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.hide(Window.java:1115)
        at java.awt.Window$1DisposeAction.run(Window.java:1188)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
        - None

"AWT-Shutdown" #14 prio=5 os_prio=0 tid=0x000000002f491000 nid=0x860 in Object.wait() [0x0000000035e7f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
        - locked <0x0000000377399608> (a java.lang.Object)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"Java2D Disposer" #13 daemon prio=10 os_prio=2 tid=0x000000002f2c8000 nid=0x3370 in Object.wait() [0x0000000035c7f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x0000000377389958> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at sun.java2d.Disposer.run(Disposer.java:148)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"SciJava-549621f3-Thread-0" #12 daemon prio=5 os_prio=0 tid=0x00000000317d9800 nid=0x5784 in Object.wait() [0x000000003254e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1257)
        - locked <0x0000000376728288> (a java.lang.Thread)
        at java.lang.Thread.join(Thread.java:1331)
        at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:107)
        at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
        at java.lang.Shutdown.runHooks(Shutdown.java:130)
        at java.lang.Shutdown.exit(Shutdown.java:178)
        - locked <0x0000000377ab8430> (a java.lang.Class for java.lang.Shutdown)
        at java.lang.Runtime.exit(Runtime.java:104)
        at java.lang.System.exit(System.java:987)
        at net.imagej.ui.swing.updater.LauncherMigrator.switchToNewLauncher(LauncherMigrator.java:398)
        at net.imagej.ui.swing.updater.LauncherMigrator.checkLaunchStatus(LauncherMigrator.java:127)
        at net.imagej.ui.swing.updater.ImageJUpdater.run(ImageJUpdater.java:85)
        at org.scijava.command.CommandModule.run(CommandModule.java:196)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
        at org.scijava.thread.DefaultThreadService$$Lambda$174/1254157360.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - <0x00000003749fcd60> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Service Thread" #11 daemon prio=9 os_prio=0 tid=0x000000002c861000 nid=0x5218 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C1 CompilerThread3" #10 daemon prio=9 os_prio=2 tid=0x000000002c7c6000 nid=0x2c0c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread2" #9 daemon prio=9 os_prio=2 tid=0x000000002c7c3000 nid=0x3b30 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread1" #8 daemon prio=9 os_prio=2 tid=0x000000002c7b5800 nid=0x80b8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 tid=0x000000002c7b4000 nid=0x254c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Attach Listener" #6 daemon prio=5 os_prio=2 tid=0x000000002c7af800 nid=0x82d4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #5 daemon prio=9 os_prio=2 tid=0x000000002c7ad000 nid=0x2598 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x000000002c7ab000 nid=0x7668 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000000002c787800 nid=0xbfc in Object.wait() [0x000000002d76f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000003749bfe80> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:188)

   Locked ownable synchronizers:
        - None

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x000000002c777800 nid=0x587c in Object.wait() [0x000000002d56f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000003749d2400> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
        - None
```

**Comment by ctrueden** [comment]
One thing I notice about that thread dump: there is an executor service thread pool thread just sitting there, probably because I did not clean up an `ExecutorService` created in the app-launcher's `Archives` utility class. Fixed now: scijava/app-launcher@8331123b426cb7b025ef53bf39b524525e9a7847. But that is unlikely to be the root cause, because the `LauncherMigrator` calls `System.exit`, and it is in the process of doing that according to the thread dump. I believe the blockage is due to:
```
"AWT-EventQueue-0" #17 prio=6 os_prio=0 tid=0x000000003342b800 nid=0x66d0 runnable [0x000000003de5d000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WComponentPeer.hide(Native Method)
        - locked <0x000000037755a9f8> (a sun.awt.windows.WFramePeer)
        at sun.awt.windows.WWindowPeer.hide(WWindowPeer.java:327)
        at sun.awt.windows.WComponentPeer.setVisible(WComponentPeer.java:125)
        at java.awt.Component.hide(Component.java:1708)
        - locked <0x00000003774da250> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.hide(Window.java:1115)
```
Because that window is stuck trying to close, it locks up the AWT event dispatch thread. But I don't know what that's happening.

As a hack workaround, you could try changing the `System.exit(0)` to:
```java
Thread exiter = new Thread(() -> System.exit(0));
exiter.setDaemon(true);
exiter.start();
```
and see if it makes a difference. Because then the Updater command would complete quickly. I'm not confident it'll fix the issue, but I'm not confident it won't...

Also grab the latest app-launcher snapshot before testing again, in case that executor service cleanup matters.

**Comment by hinerm** [comment]
>Also grab the latest app-launcher snapshot before testing again, in case that executor service cleanup matters.

Confirmed this is insufficient

>As a hack workaround, you could try changing the System.exit(0)

No luck.

>Because that window is stuck trying to close, it locks up the AWT event dispatch thread. But I don't know why that's happening.

Looks like it's back to [this issue](https://github.com/fiji/fiji/issues/347) I reported a while back and tried to work around unsuccessfully.

**Comment by hinerm** [comment]
OK I did a bit more experimentation with `IJ1Helper.dispose`, where I have all the GUI cleanup in a single `Runnable` that I am passing to the EDT (or not). I tested if the `ImageJ` frame was disposed by overriding its `dispose` method and printing before/after `super.dispose`.

All of these were tested by simply starting Fiji from the terminal and killing with `ctrl` + `c`.

| Mechanism of queueing disposal | Deadlocked? | pre-dispose message?| post-dispose message? |
|----------------------------------|---------------|-----------------------|-------------------------|
| none (`invoke` commented out) | no                  | no                              | no                                |
| `EventQueue.invokeAndWait`     | yes                 | yes                             | no                                |
| `EventQueue.invokeLater`          | no                  | yes                             | no                                |

Points I found interesting:
* with `invokeLater` it does start the `ImageJ.dispose` process but doesn't see the end.
* when we do no cleanup, *nothing* is calling `ImageJ.dispose` - so presumably with the kill signal or `System.exit` the native windows are fine releasing their resources on their own.

Since this `IJ1Helper.dispose` code path only applies when shutting down through a non-Fiji-GUI mechanism I assume it was added for `napari-imagej` concerns. IMO if `EventQueue.invokeLater` works in `napari-imagej` then we should just go with that.

**Comment by hinerm** [comment]
>IMO if EventQueue.invokeLater doesn't deadlock in napari-imagej then we should just go with that.

It does not seem to deadlock - shutdown completes successfully. However, my imagej-legacy changes had no effect on https://github.com/imagej/napari-imagej/issues/307, so I can't guarantee that it shuts down as expected with Java 21+. (although the EDT does appear to shut down so I think these issues are separate)

**Comment by hinerm** [comment]
NB: https://github.com/imagej/napari-imagej/pull/318 fixes https://github.com/imagej/napari-imagej/issues/307 when using Java 21/23

However, using this fix, if I open the ImageJ GUI inside napari and then shut down, I hang again - if I'm using my imagej-legacy changes. This suggests that my imagej-legacy fix is insufficient.

**Comment by hinerm** [comment]
Currently I'm testing with an up-to-date Fiji with the following modified components:
- https://github.com/imagej/imagej-ui-swing/pull/94/commits/fb555dc3f060c061be48d5f32ab03b90ce47156c
- https://github.com/scijava/app-launcher/commit/7e6a10750700778ba966e73a005a41d904305d74
- https://github.com/imagej/imagej-legacy/commit/76151c21275945c5d2921f6f10330b1d98b97f15

Interestingly, my deadlock "fix" is no longer sufficient to fix the shutdown deadlock after updating. Without that commit the EDT hangs here:
```
   java.lang.Thread.State: RUNNABLE
        at sun.awt.windows.WKeyboardFocusManagerPeer.getNativeFocusedWindow(Native Method)
        at sun.awt.windows.WKeyboardFocusManagerPeer.getCurrentFocusedWindow(WKeyboardFocusManagerPeer.java:66)
        at java.awt.KeyboardFocusManager.getNativeFocusedWindow(KeyboardFocusManager.java:664)
        at java.awt.KeyboardFocusManager.markClearGlobalFocusOwner(KeyboardFocusManager.java:2537)
        at java.awt.KeyboardFocusManager._clearGlobalFocusOwner(KeyboardFocusManager.java:638)
        at java.awt.KeyboardFocusManager.clearGlobalFocusOwner(KeyboardFocusManager.java:634)
        at java.awt.KeyboardFocusManager$2.run(KeyboardFocusManager.java:645)
        at java.awt.KeyboardFocusManager$2.run(KeyboardFocusManager.java:643)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.KeyboardFocusManager.clearGlobalFocusOwnerPriv(KeyboardFocusManager.java:643)
        at java.awt.Component.transferFocus(Component.java:7894)
        at java.awt.Component.hide(Component.java:1704)
       - locked <0x00000003733cda80> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.hide(Window.java:1115)
        at java.awt.Window$1DisposeAction.run(Window.java:1188)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74
```

but *with that commit* I now hang here when upgrading:
```
        at java.awt.im.InputContext.getInstance(InputContext.java:92)
        at java.awt.Window.getInputContext(Window.java:1422)
        - locked <0x00000003481ee220> (a java.lang.Object)
        at java.awt.Component.getInputContext(Component.java:6059)
        at java.awt.Component.getInputContext(Component.java:6059)
        at java.awt.Component.getInputContext(Component.java:6059)
        at java.awt.Component.removeNotify(Component.java:7020)
        - locked <0x000000037156aa18> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.removeNotify(Container.java:2823)
        - locked <0x000000037156aa18> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.removeNotify(JComponent.java:4758)
        at java.awt.Container.removeNotify(Container.java:2807)
        - locked <0x000000037156aa18> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.removeNotify(JComponent.java:4758)
        at java.awt.Container.removeNotify(Container.java:2807)
        - locked <0x000000037156aa18> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.removeNotify(JComponent.java:4758)
        at javax.swing.JRootPane.removeNotify(JRootPane.java:765)
        at java.awt.Container.removeNotify(Container.java:2807)
        - locked <0x000000037156aa18> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.removeNotify(Window.java:782)
        - locked <0x000000037156aa18> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window$1DisposeAction.run(Window.java:1190)
        at java.awt.Window.doDispose(Window.java:1206)
        at java.awt.Dialog.doDispose(Dialog.java:1198)
        at java.awt.Window.dispose(Window.java:1147)
        at java.awt.Window.disposeImpl(Window.java:1157)
        at java.awt.Window$1DisposeAction.run(Window.java:1185)
        at java.awt.Window.doDispose(Window.java:1206)
        at java.awt.Window.dispose(Window.java:1147)
        at ij.ImageJ.run(ImageJ.java:867)
        at net.imagej.legacy.IJ1Helper.lambda$dispose$1(IJ1Helper.java:253)
```

For fun I tried running as admin and upgrading, which didn't change anything.
