### ISSUE TITLE
Fiji Future: Missing javafx (FLIMJ plugin)

### ISSUE THREAD

**Issue by elevans** [fiji/fiji#376]
I just tried to use the `FLIMJ` plugin with Fiji future, but was unable to open the plugin with the following exception:

```java
(Fiji Is Just) ImageJ 2.16.0/1.54g; Java 21.0.5 [64-bit]; Linux 6.8.0-49-generic; 1314MB of 23552MB (5%)
 
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.newInstance(Class.java:706)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:304)
	at org.scijava.command.CommandInfo.createInstance(CommandInfo.java:248)
	at org.scijava.command.CommandModule.instantiateCommand(CommandModule.java:248)
	at org.scijava.command.CommandModule.<init>(CommandModule.java:98)
	at org.scijava.command.CommandInfo.createModule(CommandInfo.java:326)
	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:167)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:206)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:197)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:182)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:160)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 19 more
```

Nothing is captured when I use the `--debug ` flag. Only the above exception in a Fiji dialog/text box is displayed.

This might be more appropriate for the `flimj-ui` repo, but I imagine there are other javafx plugins that will be unhappy as well.

**Comment by ctrueden** [comment]
@elevans Please see fiji/fiji#346.
