### ISSUE TITLE
Unhandled exception at exit

### ISSUE THREAD

**Issue by anntzer** [fiji/fiji#94]
Fiji (life-line version, 06/02/2014, linux-64) raises an exception upon exit and then needs to be ctrl-c'd.

Below is the stderr output.

```
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ERROR] Skipping unsupported option -port7
Exception during disposal:
java.lang.reflect.InvocationTargetException
    at java.awt.EventQueue.invokeAndWait(EventQueue.java:1276)
    at java.awt.Window.doDispose(Window.java:1209)
    at java.awt.Window.dispose(Window.java:1147)
    at ij.ImageJ.run(ImageJ.java:767)
    at net.imagej.legacy.IJ1Helper.dispose(IJ1Helper.java:246)
    at net.imagej.legacy.ui.LegacyUI.dispose(LegacyUI.java:127)
    at org.scijava.ui.DefaultUIService.dispose(DefaultUIService.java:362)
    at org.scijava.Context.dispose(Context.java:376)
    at net.imagej.legacy.DefaultLegacyHooks.quit(DefaultLegacyHooks.java:100)
    at ij.ImageJ.quit(ImageJ.java)
    at ij.plugin.Commands.run(Commands.java:45)
    at ij.IJ.runPlugIn(IJ.java:172)
    at ij.Executer.runCommand(Executer.java:131)
    at ij.Executer.run(Executer.java:64)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null source
    at java.util.EventObject.<init>(EventObject.java:56)
    at java.awt.AWTEvent.<init>(AWTEvent.java:337)
    at java.awt.event.InvocationEvent.<init>(InvocationEvent.java:285)
    at java.awt.event.InvocationEvent.<init>(InvocationEvent.java:174)
    at sun.awt.X11.XBaseMenuWindow.dispose(XBaseMenuWindow.java:907)
    at java.awt.MenuComponent.removeNotify(MenuComponent.java:310)
    at java.awt.Menu.removeNotify(Menu.java:198)
    at java.awt.Component.removeNotify(Component.java:6991)
    at java.awt.Container.removeNotify(Container.java:2800)
    at java.awt.Window.removeNotify(Window.java:782)
    at java.awt.Frame.removeNotify(Frame.java:1041)
    at java.awt.Window$1DisposeAction.run(Window.java:1190)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:302)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by FannyGeorgi** [comment]
Hi guys, despite the optimistic comment from @anntzer, the error message still pops up.

**Comment by ctrueden** [comment]
@FannyGeorgi To be clear: the problem which @anntzer refers to as "fixed" is actually Fiji's failure to terminate as expected.

The exception given in the OP above is both unrelated and harmless. It also only occurs on Linux with Java 7, to my knowledge.

But if the message bothers or inconveniences you somehow: could you please use Help > Report a Bug to get a snapshot of your system configuration? In particular, OS and version of Java. And if you are using Java 7, could you test with Java 8? It might be fixed there; would be good to know for certain.
